name: Setup Dependencies (Windows)
inputs:
  operating-system:
    required: true
    default: "windows"
  opa-version:
    required: true
    default: "v0.60.0"
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup virtualenv
      shell: powershell
      run: |
        python -m venv .venv
        .venv\Scripts\activate.ps1

    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip install selenium

    - name: Download OPA executable
      shell: powershell
      run: |
        scubagoggles setup -m -nc -nd -d ~/scubagoggles -r ~/scubagoggles -c credentials.json
        scubagoggles getopa -v ${{ inputs.opa-version }}
