name: Setup Dependencies (Windows)
inputs:
  operating-system:
    required: true
    default: "windows"
  opa-version:
    required: true
    default: "0.60.0"
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup virtualenv
      shell: powershell
      run: |
        pip install virtualenv
        python -m venv .venv
        .venv\Scripts\activate

    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip install selenium

    - name: Download OPA executable
      shell: powershell
      run: python download_opa.py -v ${{ inputs.opa-version }} -os ${{ inputs.operating-system }}
