name: Setup Dependencies (Windows)
inputs:
  operating-system:
    required: true
    default: "windows"
  opa-version:
    required: true
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Virtual Environment Activation Definition - Windows
      shell: powershell
      run: >
        echo "SCUBAGOGGLES_ACTIVATE_VENV=.venv\Scripts\activate.ps1"
        >> "$Env:GITHUB_ENV"

    - name: Setup virtual environment and install dependencies
      shell: powershell
      run: |
        python -m venv .venv
        ${{ env.SCUBAGOGGLES_ACTIVATE_VENV }}
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip install selenium

    - name: Download OPA executable
      shell: powershell
      env:
        opa_version: ${{ inputs.opa-version == 'latest' && ' '
          || format('-v {0}', inputs.opa-version) }}
      run: |
        ${{ env.SCUBAGOGGLES_ACTIVATE_VENV }}
        scubagoggles setup -m -nc -nd -d ~/scubagoggles -r ~/scubagoggles -c credentials.json
        scubagoggles -l d getopa ${{ env.opa_version }}
