version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "pip"
    directories: 
    - "/"
    - "/scubagoggles/Testing/Functional/SmokeTests"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"