version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
      - "version bump"
    groups:
      python-dependencies:
        group-by: dependency-name
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/scubagoggles/Testing/Functional/SmokeTests"
    schedule:
      interval: "quarterly"
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "version bump"
    groups:
      python-dependencies:
        group-by: dependency-name
        patterns:
          - "*"
