# YAML basic configuration file with examples of how to specify various types
# of parameters.

# Example specifying a string parameter
outputpath: example_output

# Example specifying a list parameter
baselines: [gmail, calendar, groups, chat, drive, meet, sites, commoncontrols]

# Example specifying a boolean paramter
quiet: false