name: Setup MacOS Dependencies
inputs:
  operating-system:
    required: true
    default: "macos"
  opa-version:
    required: true
    default: "0.60.0"

runs:
  using: "composite"
  steps:
    - name: Setup virtualenv
      shell: bash
      run: |
        pip install virtualenv
        virtualenv -p python .venv
        source .venv/bin/activate
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip uninstall numpy
        pip install numpy==1.26.4
    
    - name: Download OPA executable
      shell: bash
      run: python download_opa.py -v ${{ inputs.opa-version }} -os ${{ inputs.operating-system }}