name: "\U0001F41B Bug report"
description: Describe a bug, error, unexpected behavior, or other problem
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: This issue has an informative and human-readable title.
          required: true
  - type: textarea
    attributes:
      label: ScubaGoggles Version
      description: Which ScubaGoggles version are you using?
      placeholder: |
        Activate your virtual environment (scuba-env\Scripts\activate), then run scubagoggles version locally and paste output here
        to ensure correct version is indicated.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: |
        Enter your operating system and version (e.g., Windows 10, Ubuntu 24.04 LTS, MacOS Big Sur)
    validations:
      required: true
  - type: input
    attributes:
      label: Python Version
      description: Which Python version are you using?
      placeholder: Enter your Python version (e.g., v3.10, v3.12)
    validations:
      required: true
  - type: textarea
    attributes:
      label: "\U0001F41B Summary"
      description: What's wrong? Please be specific.
      placeholder: Seeing unexpected result in the reports...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior. Any helpful log output or screenshots?
      placeholder: |
        1. Using this environment
        2. Ran scubagoggles gws with these parameters
        3. Got this specific error output at this line number

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen that didn't?
    validations:
      required: true
