name: Setup Dependencies (macOS)
inputs:
  operating-system:
    required: true
    default: "macos"
  opa-version:
    required: true
    default: "0.60.0"
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup virtualenv
      shell: bash
      run: |
        pip install virtualenv
        virtualenv -p python .venv
        source .venv/bin/activate
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip install selenium

    - name: Download OPA executable
      shell: bash
      run: |
        python download_opa.py -v ${{ inputs.opa-version }} -os ${{ inputs.operating-system }}
        chmod +x opa_darwin_amd64
