name: Setup Dependencies (macOS)
inputs:
  operating-system:
    required: true
    default: "macos"
  opa-version:
    required: true
    default: "0.60.0"
  credentials:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup virtualenv
      shell: bash
      run: |
        pip install virtualenv
        virtualenv -p python .venv
        source .venv/bin/activate
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip uninstall -y numpy
        pip install numpy==1.26.4
    
    - name: Download OPA executable
      shell: bash
      run: python download_opa.py -v ${{ inputs.opa-version }} -os ${{ inputs.operating-system }}
    
    - name: Setup credentials for service account
      shell: bash
      run: |
        # Give OPA executable execute permissions
        chmod +x opa_darwin_amd64
        # Setup credentials for service account
        echo "${{ inputs.credentials }}"
        echo "${{ inputs.credentials }}" >> credentials.json
        cat credentials.json