name: Setup Dependencies (macOS)
inputs:
  operating-system:
    required: true
    default: "macos"
  opa-version:
    required: true
    default: "v0.60.0"
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Virtual Environment Activation Definition - macOS or linux
      shell: bash
      run: >
        echo "SCUBAGOGGLES_ACTIVATE_VENV=. .venv/bin/activate"
        >> "$GITHUB_ENV"

    - name: Setup virtual environment and install dependencies
      shell: bash
      run: |
        python -m venv .venv
        ${{ env.SCUBAGOGGLES_ACTIVATE_VENV }}
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip install selenium

    - name: Download OPA executable
      shell: bash
      run: |
        ${{ env.SCUBAGOGGLES_ACTIVATE_VENV }}
        scubagoggles setup -m -nc -nd -d ~/scubagoggles -r ~/scubagoggles -c credentials.json
        scubagoggles getopa -v ${{ inputs.opa-version }}
