name: Initialize ScubaGoggles
inputs:
  python-version:
    required: true
    default: "3.12"
  cache-dependency-path:
    required: true
    default: "requirements.txt"
  operating-system:
    required: true
    default: "windows"
  opa-version:
    required: true
    default: "0.60.0"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with: 
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Setup virtualenv for Windows
      if: ${{ inputs.operating-system }} == "windows"
      shell: powershell
      run: |
        pip install virtualenv
        python -m venv .venv
        .venv\Scripts\activate
    
    - name: Setup virtualenv for MacOS
      if: ${{ inputs.operating-system }} == "macos"
      shell: bash
      run: |
        pip install virtualenv
        virtualenv -p python .venv
        source .venv/bin/activate
    
    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install .
        pip install -r requirements.txt
        pip install pytest
        pip uninstall numpy
        pip install -y numpy==1.26.4
    
    - name: Download OPA executable
      shell: powershell
      run: python download_opa.py -v ${{ inputs.opa-version }} -os ${{ inputs.operating-system }}
