name: Run ScubaGoggles
on:
  workflow_call:
    inputs:
      os:
        required: true
  workflow_dispatch:

jobs:
  run-scubagoggles-windows:
    if: ${{ inputs.os }} == "windows-latest"
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-windows-dependencies
        with:
          operating-system: "windows"
          opa-version: "0.60.0"

      - name: Execute ScubaGoggles and check for correct output
        run: |
          # Setup credentials for service account
          Set-Content -Path credentials.json -Value $env:GWS_GITHUB_AUTOMATION_CREDS
          pytest -s ./Testing/Functional/SmokeTests/ --subjectemail="$env:GWS_SUBJECT_EMAIL"

  run-scubagoggles-macos:
    if: ${{ inputs.os }} == "macos-latest"
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-macos-dependencies
        with:
          operating-system: "macos"
          opa-version: "0.60.0"

      - name: Execute ScubaGoggles and check for correct output
        run: |
          echo "in second step"

          # Give OPA executable execute permissions
          chmod +x opa_darwin_amd64
          # Setup credentials for service account
          echo $env:GWS_GITHUB_AUTOMATION_CREDS
          echo $env:GWS_GITHUB_AUTOMATION_CREDS >> credentials.json
          cat credentials.json
          #pytest -s ./Testing/Functional/SmokeTests/ --subjectemail="$env:GWS_SUBJECT_EMAIL"
